### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Kanorto** [GravitLauncher/LauncherWiki#13]
Я нашел некий баг на странице авторизации. Где написаны PasswordVerifier после phpass wordpress написано про модуль в каком-то оранжевом прямоугольнике, я попытался это исправить на гите, но тут этого нету. 
![image](https://user-images.githubusercontent.com/77388225/159052201-9ced5eb6-c596-4202-8506-a5a9306059f0.png)
Прилагаю скрины

**Comment by XJIuPa** [comment]
Если поискать, то всё можно найти

**Comment by XJIuPa** [comment]
всё есть

**Comment by dima-dencep** [comment]
@gravit0 закрой, я пофиксил это
