### ISSUE TITLE
Установка в WSL по инструкции делает недоступным WSLg X11 

### ISSUE THREAD

**Issue by zznty** [GravitLauncher/LauncherWiki#81]
Следуя инструкции на вики по установке LaunchServer, создание пользователя не по умолчанию в WSL, делает встроенное vGPU недоступным т.к не установлена переменная окружения `DISPLAY`.

Workaround есть на [странице](https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg#display-environment-variable) вики wsl.

Как решение могу предложить указать это явно на [странице](https://gravitlauncher.com/clientbuild/#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-x11-forwarding) вики по MirrorHelper (сейчас там явно указаны шаги только в случае подключения по SSH)

**Comment by gru2007** [comment]
Я лично, решил эту проблему установкой на свой домашний Linux LaunchServer, специально для сборки клиента. После чего, просто скопировал его на сервер.

**Comment by microwin7** [comment]
Я ничего не понял, что вы написали. Особенно что за WSLg в заголовке. И в чём проблема установить переменную окружения, так же совсем непонятно

**Comment by Wonkiest29** [comment]
@gravit0 закрывай

**Comment by microwin7** [comment]
> Следуя инструкции на вики по установке LaunchServer, создание пользователя не по умолчанию в WSL, делает встроенное vGPU недоступным т.к не установлена переменная окружения `DISPLAY`.
> 
> Workaround есть на [странице](https://github.com/microsoft/wslg/wiki/Diagnosing-%22cannot-open-display%22-type-issues-with-WSLg#display-environment-variable) вики wsl.
> 
> Как решение могу предложить указать это явно на [странице](https://gravitlauncher.com/clientbuild/#%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5-x11-forwarding) вики по MirrorHelper (сейчас там явно указаны шаги только в случае подключения по SSH)

Отправь PR с прикреплением данной статьи как примечание по использованию X11 Forwarding

**Comment by Wonkiest29** [comment]
[PR](https://github.com/GravitLauncher/LauncherWiki/pull/83) добавил
